import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UserProvider } from '@/context/UserContext'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link className='mx-2 text-red-600' href="/auth/registrarse">Registrarse</Link>
        <Link className='mx-2 text-red-600' href="/auth/login">Iniciar sesión</Link>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  )
}
